package com.livingmods.common.model;

/** Typed physical outcomes reported Minecraft → sidecar. */
public enum PhysicalOutcomeType {
    ENTITY_KILLED,
    ENTITY_DESPAWNED,
    CARAVAN_DAMAGED,
    CARAVAN_ARRIVED,
    CARAVAN_ATTACKED,
    CAMP_DESTROYED,
    CAMP_CLEARED,
    STRUCTURE_DAMAGED,
    STRUCTURE_COMPLETED,
    STRUCTURE_DESTROYED,
    SIEGE_BREACH,
    TASK_ITEM_DELIVERED,
    TASK_OBJECTIVE_EVIDENCE,
    INTENT_MATERIALIZED,
    INTENT_BLOCKED,
    INTENT_FAILED,
    ARMY_CASUALTIES,
    GUARD_ATTACKED,
    TRADE_COMPLETED,
    SETTLEMENT_FOUNDED,
    CRIME_COMMITTED,
    PLAYER_REPUTATION_ACTION,
    PROJECTION_SYNC
}
