package com.livingmods.common.event;

public enum CivilizationEventType {
    SETTLEMENT_DEVELOPMENT_CHANGED,
    CONSTRUCTION_REQUIRED,
    CARAVAN_APPROACHING_PHYSICAL_REGION,
    ARMY_ENTERING_PHYSICAL_REGION,
    WAR_STARTED,
    WAR_ENDED,
    RULER_DIED,
    SUCCESSION_RESOLVED,
    EPIDEMIC_STARTED,
    EPIDEMIC_ENDED,
    REFUGEE_GROUP_ENTERING_REGION,
    MARKET_CRISIS,
    BANDIT_ACTIVITY_CHANGED,
    TREATY_SIGNED,
    TREATY_BROKEN,
    MIGRATION_STARTED,
    SETTLEMENT_FOUNDED,
    SETTLEMENT_DESTROYED,
    REBELLION_STARTED,
    TECHNOLOGY_DISCOVERED,
    HISTORICAL_MONUMENT_CREATED,
    PLAYER_REPUTATION_CHANGED,
    SAVE_COMPLETED,
    SIDECAR_READY,
    SIDECAR_DEGRADED
}
